[project]
name = "mcp_servers_and_a2a_utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
"deepeval",
#"arize-phoenix-evals>=2.0.0",
"arize-otel",
"arize-phoenix",
"openinference-instrumentation-openai", 
"opentelemetry-sdk",
 "opentelemetry-exporter-otlp",
 "arize-phoenix",
  "arize-phoenix-evals",
"llama-index-core", #Core LlamaIndex Framework
"llama-index", #Simplified inst
"llama-index-llms-openai",
"llama-index-embeddings-openai",
"llama-index-embeddings-bedrock",
"llama-index-vector-stores-opensearch",
"langchain-anthropic>=1.3.1",
"llama-index-llms-bedrock-converse",
"llama-index-readers-file",
"llama-index-retrievers-bm25",
"llama-index-vector-stores-qdrant",
"llama-index-question-gen-openai",
"qdrant-client",
"rank-bm25",
"sourcemapr",
"python-docx",
"langchain",
#"langchain-community",
  "langchain-community>=0.3.29",
"langchain-core",
"langchain-huggingface",
"langchain-mcp-adapters",
"langchain-text-splitters",
"PyPDF2==3.0.1",
"pypdf==5.5.0",
"sentence-transformers==4.1.0",
"deepagents",
"tavily-python",
"langchain-google-community[gmail]",
"langchain-google-community[calendar]",
"langchain-tavily>=0.2.11",
 "langsmith>=0.4.30",
"openevals>=0.1.0",
"arxiv>=2.2.0",
"jupyter>=1.1.1",
"langchain",
"fastmcp",
"google-adk==1.13.0",
"google-genai>=1.17.0",
"click>=8.1.8",
"httpx>=0.28.1",
"langchain-google-genai>=2.0.10",
"langgraph>=0.3.18",
"langchain-openai>=0.1.0",
"pydantic>=2.10.6",
"python-dotenv>=1.1.0",
"uvicorn>=0.34.2",
"sse-starlette>=2.3.6",
"starlette>=0.46.2",
"a2a-sdk", 
"httpx", 
"uvicorn",
"a2a-sdk[http-server]",
"strands-agents",
"strands-agents-tools",
"strands-agents[a2a]",
"litellm",
"ipykernel",
"pymupdf>=1.26.4",
"pyppeteer",
 "langchain-qdrant>=0.2.1",
 "langchain-openai>=0.3.33",
 "langchain_chroma",
 #"chromadb",
 "langchain-core",
 "fastapi",
 "uvicorn",
"ipykernel>=7.1.0",
"ipywidgets>=8.1.7",
"jupyterlab>=4.4.10",
"python-dotenv>=1.2.1",
"textstat>=0.7.10",
"youtube-transcript-api>=1.2.3",
"gradio",
"python-docx",
"slowapi",
"redis",
"ragas",
"fastmcp>=0.5.0",
"httpx>=0.24.0",
"mysql-connector-python>=8.2.0",
"python-dotenv>=1.0.0",
 ]

[tool.uv.workspace]
members = [
    "huggingface-utils",
    "hugging_repo/huggingface_smolagents_utils",
    "sai_projects/Langgraph_AgentMiddleware",
]
